on: [workflow_dispatch]

name: deploy

jobs:
  deploy:
    name: Build and publish to GitHub pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    permissions:
       contents: write
       pages: write
       id-token: write

    # Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
    # However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
    concurrency:
      group: "pages"
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v7.0.1
        with:
           fetch-depth: 0

      - uses: dtolnay/rust-toolchain@stable
        with:
           targets: wasm32-unknown-unknown

      - name: Install protoc compiler
        run: |
          sudo apt-get update
          sudo apt-get install protobuf-compiler

      - uses: jetli/wasm-pack-action@v0.4.0
        with:
           version: 'latest'

      - uses: taiki-e/install-action@v2.85.11
        with:
           tool: zola

      # This builds our Rust code as WASM, then builds the version of the python construct library
      # needed by pywidevine that isn't available as a prebuilt wheel on PyPI. We use a prebuilt
      # version of pyodide distributed on a CDN.
      - name: Build bundle
        run: |
           rm -rf dist/
           (cd www-zola && zola build --output-dir ../dist)
           wasm-pack build --release --target web
           # The generated WebAssembly
           cp -r pkg dist
           find dist -type d -print0 | xargs -0 chmod 755
           find dist -type f -print0 | xargs -0 chmod 644
           wget -q -O /tmp/construct.tgz https://files.pythonhosted.org/packages/b6/2c/66bab4fef920ef8caa3e180ea601475b2cbbe196255b18f1c58215940607/construct-2.8.8.tar.gz
           tar xzf --directory=/tmp construct-2.8.8.tar.gz
           (cd /tmp/construct-2.8.8 && python3 setup.py bdist_wheel)
           cp /tmp/construct-2.8.8/dist/construct-2.8.8-py2.py3-none-any.whl dist

      - uses: actions/configure-pages@v6

      - uses: actions/upload-pages-artifact@v5
        with:
          path: './dist'
          retention-days: 2

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
        

